seed: 42
optimizer:
  type: adam
  learning_rate: 0.003
regularization:
  l2_weight_decay: 0.0001
  dropout_rate: 0.0
model:
  hidden_neurons: 25
data:
  cases_per_disease: 50
calibration:
  temperature: 1.0

