name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (root)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dependencies (medical model)
        run: |
          pip install -r medical_diagnosis_model/requirements.txt

      - name: Validate sample datasets
        run: |
          python medical_diagnosis_model/data/validate_cases.py medical_diagnosis_model/data/samples/cases_v0.1.jsonl

      - name: Run unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/medical_diagnosis_model
          MDM_QUICK_TRAIN: '1'
        run: |
          python -m pytest -q medical_diagnosis_model/tests/test_api_phase1.py


